# Generated by Django 3.2.4 on 2021-06-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='screenslotmoviemapping',
            unique_together={('screen', 'slot', 'movie')},
        ),
        migrations.AlterUniqueTogether(
            name='seats',
            unique_together={('row', 'index', 'screen')},
        ),
    ]
