# Generated by Django 3.2.4 on 2021-06-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbs', '0002_auto_20210617_2059'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='screenslotmoviemapping',
            unique_together={('screen', 'slot')},
        ),
    ]
